services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: local-server
    hostname: api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.host.local`)"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
    ports:
      - '8000:8000'
    volumes:
      - '.:/var/www/html'
    networks:
      - api


networks:
  api:
    driver: bridge
